### ISSUE TITLE
Pre-commit 

### ISSUE THREAD

**Issue by Bizilizi** [miki725/importanize#59]
Hello. Could you please suggest for some reasons why this config in `pre-commit-config.yaml` does not work:
```
repos:
  - repo: https://github.com/miki725/importanize/
    rev: 'master'
    hooks:
      - id: importanize
        name: importanize
        entry: python -m importanize
        language: python
        language_version: python3
        types: [python]
        args: [-v, --no-subconfig]
        additional_dependencies: [click, pluggy, pyflakes]
```
I always get 'Passed' from importanize hook, but no changes in files
